# Generated by Django 4.0.4 on 2023-01-24 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название меню')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LevelTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Имя второго уровня')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Второй уровень вложенности',
                'verbose_name_plural': 'Вторые уровни вложенности',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LevelThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Имя третьего уровня')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.leveltwo', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Третий уровень вложенности',
                'verbose_name_plural': 'Третие уровни вложенности',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LevelOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Имя первого уровня')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu', verbose_name='Имя меню')),
            ],
            options={
                'verbose_name': 'Первый уровень вложенности',
                'verbose_name_plural': 'Первые уровни вложенности',
                'ordering': ['id'],
            },
        ),
    ]
