# Generated by Django 4.0.4 on 2023-01-25 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveltwo',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.levelone', verbose_name='Родитель'),
        ),
    ]
