# Generated by Django 4.0.4 on 2023-01-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_leveltwo_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LevelThree',
        ),
    ]
